version: '3.7'

services: 
    django:
        build: ./app

        command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
        working_dir: /usr/src/app
        volumes: 
            - ./app:/usr/src/app
            - static_volume:/usr/src/app/staticfiles
            - media_volume:/usr/src/app/mediafiles
        expose: 
            - 8000
        env_file: 
            - ./.env.dev
        depends_on: 
            - postgres
        networks: 
            - front
            - back
    
    postgres: 
        image: postgres:12.0-alpine
        volumes: 
            - db_data:/usr/src/app
            - './initdb/:/docker-entrypoint-initdb.d'
        env_file: 
            - ./.env.dev
        networks: 
            - back
    nginx: 
        build: ./nginx
        volumes: 
            - static_volume:/usr/src/app/staticfiles
            - media_volume:/usr/src/app/mediafiles
        ports: 
            - 1340:80
        depends_on: 
            - django
        networks: 
            - front

volumes: 
    db_data:
    static_volume:
    media_volume:

networks: 
    front:
        external: false
    back:
        external: false